# Generated by Django 5.2.8 on 2025-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_webhooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('SENT', 'Enviada'), ('RECEIVED', 'Recebida')], max_length=10),
        ),
    ]
